[project]
name = "hello-gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.0"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "fastmcp>=2.11.3",
    "google-genai>=1.29.0",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.43",
]
